version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=your_production_secret_key
      - AI_DETECTION_API_KEY=your_api_key
      - AI_DETECTION_API_ENDPOINT=https://api.example.com/detect
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://YOUR_SERVER_IP_OR_DOMAIN:8081/api
    restart: always 